spring:
  application:
    name: order-service
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:postgresql://localhost:5433/order-service
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8081

inventory:
  url: http://localhost:8082